@MLModelAPI_HostAddress = http://localhost:5185

GET {{MLModelAPI_HostAddress}}/weatherforecast/
Accept: application/json


###


POST {{{MLModelAPI_HostAddress}}}/api/Image/predict
Accept: image/jpeg

###
